sudo: required

language: node

services:
  - docker

install:
  - docker --version  # document the version travis is using
  - docker build -t smartmeter-vzlogger-rpi .

script:
  - docker run --rm smartmeter-vzlogger-rpi date
#after_success:
