sudo: required

language: node

services:
  - docker

install:
  - docker --version  # document the version travis is using
  - docker build -t smartmeter-vzlogger .

script:
  - docker run --rm smartmeter-vzlogger date
#after_success:
